services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: school-postgres
    environment:
      POSTGRES_USER: school_admin
      POSTGRES_PASSWORD: school_password_2024
      POSTGRES_DB: school_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: school-redis
    ports:
      - "6379:6379"
    networks:
      - school-network

  # Kafka Message Broker
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: school-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - school-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: school-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - school-network

  # LocalStack for S3 (Development)
  localstack:
    image: localstack/localstack:2.2
    container_name: school-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
      - school-network

  # Prometheus (Monitoring)
  prometheus:
    image: prom/prometheus:latest
    container_name: school-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - school-network

  # Grafana (Monitoring Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: school-grafana
    ports:
      - "3009:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - school-network

volumes:
  postgres_data:
  redis_data:
  localstack_data:
  prometheus_data:
  grafana_data:

networks:
  school-network:
    driver: bridge