apiVersion: v2
name: school-management
description: A Helm chart for School Management System
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami" 
    condition: redis.enabled
  - name: kafka
    version: "26.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled

keywords:
  - school
  - management
  - education
  - microservices
  - nestjs

maintainers:
  - name: School Management Team
    email: admin@school-management.com